name: release
on:
  release:
    types:
      - created

jobs:
  releases-matrix:
    name: Release Go Binary
    runs-on: ubuntu-latest
    strategy:
      matrix:
        goos: [linux, windows, darwin]
        goarch: [arm, arm64, amd64]
        exclude:  
          - goarch: "arm"
            goos: darwin
          - goarch: "arm"
            goos: windows
          - goarch: "arm64"
            goos: windows
    steps:
    - uses: actions/checkout@v2
    - uses: wangyoucao577/go-release-action@v1.20
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        goos: ${{ matrix.goos }}
        goarch: ${{ matrix.goarch }}
        project_path: "./"
        binary_name: "rekoda"
        extra_files: LICENSE README.md
